[tools]
"gem:kamal" = "latest"
node = "16"
"npm:figlet" = "latest"

[hooks]
enter = """
figlet waifu-trader
echo "node: $(node --version)"
echo "npm: v$(npm --version)"
"""

[settings]
experimental = true
