name: Remix

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
      with:
        node-version: '16'
        check-latest:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Install node dependencies
      run: npm ci

    - name: Run unit tests
      run: npm test
